name: Android Watch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 添加调试步骤
      - name: Enable Debug Log
        run: |
          echo "::debug::Enable Gradle Debug Logging"
          echo "DEBUG=true" >> $GITHUB_ENV

      - name: Print Gradle Version
        run: ./gradlew --version

      - name: Print Kotlin Version
        run: ./gradlew dependencies | grep kotlin

      - name: Print Dependencies
        run: ./gradlew dependencies

      - name: Build Watch Debug APK
        run: ./gradlew :watch:assembleDebug -Dorg.gradle.logging.level=DEBUG

      - name: Upload Watch Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: watch-debug-apk
          path: watch/build/outputs/apk/debug/watch-debug.apk
